FPS = 5
MIN_PLAYERS_TO_START = 1

CLEAR_CHARACTER = "\033[2J\r"
CURSOR_PREVIOUS_LINE = "\033[F"
KEY_UP = b"\x1b[A"
KEY_DOWN = b"\x1b[B"
KEY_RIGHT = b"\x1b[C"
KEY_LEFT = b"\x1b[D"

FULL_BLOCK = "\u2588"

PLAYER_UP =    "\u25B2"  # ▲
PLAYER_DOWN =  "\u25BC"  # ▼
PLAYER_LEFT =  "\u25C0"  # ◀
PLAYER_RIGHT = "\u25B6"  # ▶
PLAYER_STOP =  "\u25C6"  # ◆

TRAIL_HORIZONTAL = "\u2501"  # ━
TRAIL_VERTICAL =   "\u2503"  # ┃
TRAIL_LEFT_DOWN =  "\u2513"  # ┓
TRAIL_LEFT_UP =    "\u251B"  # ┛
TRAIL_RIGHT_DOWN = "\u250F"  # ┏
TRAIL_RIGHT_UP =   "\u2517"  # ┗

FRAME_HORIZONTAL    = "\u2550" # ═
FRAME_VERTICAL      = "\u2551" # ║
FRAME_TOP_LEFT      = "\u2554" # ╔
FRAME_TOP_RIGHT     = "\u2557" # ╗
FRAME_BOTTOM_LEFT   = "\u255A" # ╚
FRAME_BOTTOM_RIGHT  = "\u255D" # ╝
FRAME_LEFT_T        = "\u2563" # ╣
FRAME_RIGHT_T       = "\u2560" # ╠
FRAME_TOP_T         = "\u2566" # ╦
FRAME_BOTTOM_T      = "\u2569" # ╩

EMPTY_SQUARE = " "

SPAWN_MARGINS = 2
